services:
  playground:
    image: playground
    build:
      context: .
      dockerfile: ./demo-api/Dockerfile
    env_file:
      - ./demo-api/.production.env
    ports:
      - 3000:3000
