services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - "./mongo-db/data:/data/db"
      - "./mongo-db/logs:/var/log/mongodb"
    env_file:
      - ./mongo-db/.development.env
  playground:
    image: playground
    build:
      context: .
      dockerfile: ./demo-api/Dockerfile
    env_file:
      - ./demo-api/.development.env
    ports:
      - 3000:3000
    command: ["npm", "run", "debug"]
