services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - "./mongo-db/data:/data/db"
      - "./mongo-db/logs:/var/log/mongodb"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: "test"
  playground:
    image: playground
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .development.env
    environment:
      MONGODB_ADDRESS: "mongodb"
      MONGO_USERNAME: root
      MONGO_PASSWORD: "test"
    ports:
      - 3000:3000
    command: ["npm", "run", "debug"]
